baseURL = 'https://blog.cloudsftp.de/'
languageCode = 'en-us'
title = "cloudsftp's Blog"
theme = 'hello-friend-ng'
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Tales from da Lab"
  disableReadOtherPosts = false
  enableSharingButtons = false
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "cloudsftp's blog and personal website"
  keywords = "homepage, blog, cloud, linux, OSS, open source"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "cloudsftp's Blog"
    subtitle = "Math Ethusiast"
    keywords = "Open Source Software"
    #copyright = ''
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cloudsftp@website$ cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[markup.goldmark.renderer]
unsafe= true
