baseURL = 'https://www.cloudsftp.de/'
languageCode = 'en-us'
title = "clouds' Blog"
theme = 'hello-friend-ng'
paginate     = 10

[params]
  dateform        = "2006-01-02"
  dateformShort   = "01-02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Tales from da Lab"
  disableReadOtherPosts = false
  enableSharingButtons = false
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "clouds' blog and personal website"
  keywords = "homepage, blog, cloud, linux, OSS, open source"
  images = [""]

  backgroundImage = "background-images/mandelbrot.jpg"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    [languages.en.params]
      title = "clouds' Blog"
      subtitle = "Tales from da Lab"
      keywords = "Open Source Software"
      #copyright = ''
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
      readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cloudsftp@website$ cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier  = "blog"
    name        = "Blog"
    url         = "/posts"
  
  [[menu.main]]
    identifier  = "about"
    name        = "About"
    url         = "/about"

[markup.goldmark.renderer]
    unsafe= true

[markup]
  [markup.highlight]
    style = "github-dark"

[Author]
    name = "Fabian Weik"
    email = "fabian.weik@protonmail.com"
